// Skriv den rette datatype og et passende variabelnavn foran denne værdi: String teacherName= "Tess Løvgreen"
String teacherName = "Tess Løvgreen";
int daysInYear = 365;
String capital = "København";
boolean areYouTess = true;
int minutesADay = 60*24;
double decimal = 22.12;
String userMessage = "Hej, jeg heddder "+teacherName;
boolean areYouTine = false;
float plusDecimal = 2.2 + 33;
char pressSKey = 'S';
